FROM registry.redhat.io/ubi10/go-toolset:10.1 AS builder
USER 0
WORKDIR /go/src/github.com/openshift/secrets-store-csi-driver-operator
COPY . .
RUN make
RUN go version -m secrets-store-csi-driver-operator

FROM registry.redhat.io/ubi10-minimal:10.1
COPY --from=builder /go/src/github.com/openshift/secrets-store-csi-driver-operator/secrets-store-csi-driver-operator /usr/bin/
ENTRYPOINT ["/usr/bin/secrets-store-csi-driver-operator"]
LABEL io.k8s.display-name="OpenShift Secrets Store CSI Driver Operator" \
	io.k8s.description="The Secrets Store CSI Driver Operator installs and maintains the Secrets Store CSI Driver on a cluster."
