apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets-store.csi.k8s.io
  annotations:
    csi.openshift.io/managed: "true"
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: "restricted"
spec:
  podInfoOnMount: true
  attachRequired: false
  fsGroupPolicy: File
  volumeLifecycleModes:
  - Ephemeral
  tokenRequests:
  - audience: api://AzureADTokenExchange
